export const COLOMBIAN_CITIES = [
  "Abriaquí",
  "Acacías",
  "Aguachica",
  "Aguada",
  "Aguadas",
  "Aguazul",
  "Agustín Codazzi",
  "Aipe",
  "Albania",
  "Albania (La Guajira)",
  "Albania (Santander)",
  "Albán",
  "Alcala",
  "Aldana",
  "Alejandria",
  "Algarrobo",
  "Algeciras",
  "Almaguer",
  "Almeida",
  "Alpujarra",
  "Altamira",
  "Alto Baudó",
  "Alto del Rosario",
  "Altos del Rosario",
  "Alvarado",
  "Amagá",
  "Amalfi",
  "Ambalema",
  "Anapoima",
  "Ancuya",
  "Andalucía",
  "Andes",
  "Angelópolis",
  "Angostura",
  "Anolaima",
  "Anorí",
  "Anserma",
  "Ansermanuevo",
  "Anzoátegui",
  "Apartadó",
  "Apulo",
  "Aquitania",
  "Aracataca",
  "Arauca",
  "Arauquita",
  "Arbeláez",
  "Arboleda",
  "Arboletes",
  "Arboleya",
  "Arcabuco",
  "Arenal",
  "Argelia",
  "Argelia (Antioquia)",
  "Argelia (Cauca)",
  "Ariguaní",
  "Arjona",
  "Armenia",
  "Armenia (Antioquia)",
  "Armenia (Quindío)",
  "Armero",
  "Arroyohondo",
  "Astrea",
  "Ataco",
  "Atánquez",
  "Atrato",
  "Ayapel",
  "Bagadó",
  "Bahía Solano",
  "Bajo Baudó",
  "Balboa",
  "Balboa (Cauca)",
  "Balboa (Risaralda)",
  "Baranoa",
  "Baraya",
  "Barbacoas",
  "Barbosa",
  "Barbosa (Antioquia)",
  "Barbosa (Santander)",
  "Barichara",
  "Barranca de Upía",
  "Barrancabermeja",
  "Barrancas",
  "Barranco de Loba",
  "Barranquilla",
  "Becerril",
  "Belalcázar",
  "Bello",
  "Belmira",
  "Beltrán",
  "Berbeo",
  "Betania",
  "Betulia",
  "Bituima",
  "Boavita",
  "Bochalema",
  "Bogotá",
  "Bojacá",
  "Bojayá",
  "Bolívar",
  "Bolívar (Antioquia)",
  "Bolívar (Cauca)",
  "Bolívar (Santander)",
  "Bosconia",
  "Boyacá",
  "Bramadora",
  "Briceño",
  "Briceño (Antioquia)",
  "Briceño (Boyacá)",
  "Bucaramanga",
  "Bucarasica",
  "Buenaventura",
  "Buenavista",
  "Buenavista (Boyacá)",
  "Buenavista (Córdoba)",
  "Buenavista (Quindío)",
  "Buenavista (Sucre)",
  "Buenos Aires",
  "Buesaco",
  "Buga",
  "Bugalagrande",
  "Buriticá",
  "Busbanzá",
  "Cáceres",
  "Cachipay",
  "Cachira",
  "Cacota",
  "Caicedo",
  "Caicedonia",
  "Caimito",
  "Cajamarca",
  "Cajibío",
  "Cajicá",
  "Calamar",
  "Calamar (Bolívar)",
  "Calamar (Guaviare)",
  "Calarcá",
  "Caldas",
  "Caldas (Antioquia)",
  "Caldas (Boyacá)",
  "Caldono",
  "California",
  "Calima",
  "Caloto",
  "Campamento",
  "Campo de la Cruz",
  "Campoalegre",
  "Campohermoso",
  "Canalete",
  "Candelaria",
  "Candelaria (Atlántico)",
  "Candelaria (Valle del Cauca)",
  "Cantagallo",
  "Cantón de San Pablo",
  "Caparrapí",
  "Capitanejo",
  "Caquetá",
  "Caqueza",
  "Caracolí",
  "Caramanta",
  "Carcasí",
  "Carepa",
  "Carmen de Apicalá",
  "Carmen de Bolívar",
  "Carmen de Carupa",
  "Carmen del Darién",
  "Carolina",
  "Cartagena",
  "Cartagena del Chairá",
  "Cartago",
  "Carurú",
  "Casabianca",
  "Castilla la Nueva",
  "Caucasia",
  "Cañasgordas",
  "Cereté",
  "Cerinza",
  "Cerrito",
  "Cerro San Antonio",
  "Chachagüí",
  "Chaguaní",
  "Chalán",
  "Chaparral",
  "Charalá",
  "Charta",
  "Chía",
  "Chibolo",
  "Chiguaná",
  "Chimá",
  "Chimichagua",
  "Chinácota",
  "Chinavita",
  "Chinchiná",
  "Chinú",
  "Chipatá",
  "Chiquinquirá",
  "Chiriguaná",
  "Chiscas",
  "Chita",
  "Chitagá",
  "Chitaraque",
  "Chivatá",
  "Chivor",
  "Choachí",
  "Chocontá",
  "Choró",
  "Chovó",
  "Ciénaga",
  "Ciénaga (Boyacá)",
  "Ciénaga de Oro",
  "Cimitarra",
  "Circasia",
  "Cisneros",
  "Ciudad Bolívar",
  "Clemencia",
  "Cocorná",
  "Coello",
  "Cogua",
  "Colombia",
  "Colón",
  "Colón (Putumayo)",
  "Colosó",
  "Comfacundi",
  "Concepción",
  "Concepción (Antioquia)",
  "Concepción (Santander)",
  "Concordia",
  "Concordia (Antioquia)",
  "Concordia (Magdalena)",
  "Condoto",
  "Confines",
  "Consacá",
  "Contadero",
  "Contratación",
  "Convención",
  "Copacabana",
  "Coper",
  "Cordobá",
  "Corinto",
  "Corozal",
  "Corral",
  "Cota",
  "Cotorra",
  "Covarachía",
  "Coveñas",
  "Coyaima",
  "Cravo Norte",
  "Cuaspud",
  "Cubará",
  "Cubarral",
  "Cucaita",
  "Cucunubá",
  "Cucutilla",
  "Cuitiva",
  "Cumaral",
  "Cumaribo",
  "Cumbal",
  "Cumbitara",
  "Cunday",
  "Curillo",
  "Curiti",
  "Curumaní",
  "Cútiva",
  "Dabeiba",
  "Dagua",
  "Dibulla",
  "Distracción",
  "Dolores",
  "Don Matías",
  "Dosquebradas",
  "Duitama",
  "Durania",
  "Ebéjico",
  "El Águila",
  "El Bagre",
  "El Banco",
  "El Cairo",
  "El Calvario",
  "El Carmen",
  "El Carmen de Atrato",
  "El Carmen de Bolívar",
  "El Carmen de Chucurí",
  "El Carmen de Viboral",
  "El Castillo",
  "El Cerrito",
  "El Charco",
  "El Cocuy",
  "El Copey",
  "El Doncello",
  "El Dovio",
  "El Espino",
  "El Guacamayo",
  "El Guamo",
  "El Litoral",
  "El Peñol",
  "El Peñón",
  "El Peñón (Bolívar)",
  "El Peñón (Santander)",
  "El Piñón",
  "El Playón",
  "El Retén",
  "El Retorno",
  "El Roble",
  "El Rosal",
  "El Rosario",
  "El Tablón de Gómez",
  "El Tambo",
  "El Tambo (Cauca)",
  "El Tambo (Nariño)",
  "El Tarra",
  "El Zulia",
  "Elías",
  "Encino",
  "Enciso",
  "Entrerríos",
  "Envigado",
  "Espinal",
  "Facatativá",
  "Falan",
  "Filadelfia",
  "Filandia",
  "Firavitoba",
  "Flandes",
  "Florencia",
  "Florencia (Caquetá)",
  "Floresta",
  "Florida",
  "Floridablanca",
  "Florián",
  "Fonseca",
  "Fortul",
  "Fosca",
  "Francisco Pizarro",
  "Fredonia",
  "Fresno",
  "Frontino",
  "Fuente de Oro",
  "Fundación",
  "Funes",
  "Funza",
  "Fusagasugá",
  "Gachalá",
  "Gachancipá",
  "Gachantivá",
  "Gachetá",
  "Galapa",
  "Galeras",
  "Gámbita",
  "Gameza",
  "Ganar",
  "Garagoa",
  "Garzón",
  "Gigante",
  "Ginebra",
  "Giraldo",
  "Girardot",
  "Girardota",
  "Gómez Plata",
  "Gonzalez",
  "Gramalote",
  "Granada",
  "Granada (Antioquia)",
  "Granada (Cundinamarca)",
  "Granada (Meta)",
  "Guaca",
  "Guacamayas",
  "Guacarí",
  "Guachavés",
  "Guachucal",
  "Guadalupe",
  "Guadalupe (Antioquia)",
  "Guadalupe (Huila)",
  "Guadalupe (Santander)",
  "Guaduas",
  "Guaitarilla",
  "Gualmatán",
  "Guamal",
  "Guamal (Magdalena)",
  "Guamal (Meta)",
  "Guamo",
  "Guapí",
  "Guapotá",
  "Guapotá (Santander)",
  "Guasca",
  "Guatapé",
  "Guataquí",
  "Guatavita",
  "Guateque",
  "Guavatá",
  "Guayabal de Síquima",
  "Guayabetal",
  "Guayatá",
  "Güepsa",
  "Guicán",
  "Gutiérrez",
  "Guática",
  "Güicán",
  "Hacarí",
  "Hatillo de Loba",
  "Hato",
  "Hato Corozal",
  "Hato del Corozal",
  "Heliconia",
  "Herrán",
  "Hervideros",
  "Hispania",
  "Hobo",
  "Honda",
  "Ibagué",
  "Icononzo",
  "Iles",
  "Imúes",
  "Inírida",
  "Inzá",
  "Inzá (Cauca)",
  "Ipiales",
  "Isnos",
  "Istmina",
  "Itagüí",
  "Ituango",
  "Izá",
  "Jambaló",
  "Jamundí",
  "Jardín",
  "Jenesano",
  "Jericó",
  "Jericó (Antioquia)",
  "Jericó (Boyacá)",
  "Jesús María",
  "Jordán",
  "Juan de Acosta",
  "Junín",
  "Juradó",
  "La Apartada",
  "La Argentina",
  "La Belleza",
  "La Calera",
  "La Capilla",
  "La Ceja",
  "La Celia",
  "La Cruz",
  "La Cumbre",
  "La Dorada",
  "La Esperanza",
  "La Gloria",
  "La Guaira",
  "La Jagua de Ibirico",
  "La Jagua del Pilar",
  "La Llanada",
  "La Macarena",
  "La Merced",
  "La Mesa",
  "La Montañita",
  "La Palma",
  "La Palma (Cundinamarca)",
  "La Paz",
  "La Paz (Cesar)",
  "La Paz (Santander)",
  "La Peña",
  "La Pintada",
  "La Plata",
  "La Playa",
  "La Primavera",
  "La Salina",
  "La Sierra",
  "La Tebaida",
  "La Tola",
  "La Unión",
  "La Unión (Antioquia)",
  "La Unión (Cauca)",
  "La Unión (Nariño)",
  "La Unión (Sucre)",
  "La Unión (Valle del Cauca)",
  "La Uvita",
  "La Vega",
  "La Vega (Cauca)",
  "La Vega (Cundinamarca)",
  "La Victoria",
  "La Victoria (Arauca)",
  "La Victoria (Valle del Cauca)",
  "La Virginia",
  "Labateca",
  "Labranzagrande",
  "Landázuri",
  "Lebrija",
  "Leiva",
  "Lejanías",
  "Lenguazaque",
  "Leticia",
  "Liborina",
  "Linares",
  "Lloró",
  "Lorica",
  "Los Andes",
  "Los Córdobas",
  "Los Palmitos",
  "Los Patios",
  "Los Santos",
  "Lourdes",
  "Luruaco",
  "Lutió",
  "Macanal",
  "Macaravita",
  "Maceo",
  "Machetá",
  "Madrid",
  "Magangué",
  "Magüí",
  "Mahates",
  "Maicao",
  "Majagual",
  "Malambo",
  "Mallama",
  "Manatí",
  "Manaure",
  "Manaure Balcón del Cesar",
  "Maní",
  "Manizales",
  "Manta",
  "Manzanares",
  "Manzanares (Caldas)",
  "Maripí",
  "Mariquita",
  "Marmato",
  "Marquetalia",
  "Marsella",
  "Marulanda",
  "María la Baja",
  "Matanzas",
  "Medellín",
  "Medina",
  "Medio Atrato",
  "Medio Baudó",
  "Medio San Juan",
  "Melgar",
  "Mercaderes",
  "Mesetas",
  "Milán",
  "Miraflores",
  "Miraflores (Boyacá)",
  "Miraflores (Guaviare)",
  "Miranda",
  "Mistrató",
  "Mitú",
  "Mocoa",
  "Mogotes",
  "Molagavita",
  "Momil",
  "Mompós",
  "Mongua",
  "Monguí",
  "Moniquirá",
  "Montebello",
  "Montecristo",
  "Montelíbano",
  "Montenegro",
  "Monteria",
  "Monterrey",
  "Monterrey (Casanare)",
  "Morales",
  "Morales (Bolívar)",
  "Morales (Cauca)",
  "Morelia",
  "Morroa",
  "Mosquera",
  "Mosquera (Cundinamarca)",
  "Mosquera (Nariño)",
  "Motavita",
  "Mozo",
  "Municipio",
  "Murillo",
  "Murindó",
  "Mutatá",
  "Mutiscua",
  "Muzo",
  "Nariño",
  "Nariño (Antioquia)",
  "Nariño (Cundinamarca)",
  "Nariño (Nariño)",
  "Natagaima",
  "Nechí",
  "Necoclí",
  "Neira",
  "Neiva",
  "Nemocón",
  "Nilo",
  "Nimaima",
  "Nobsa",
  "Nocaima",
  "Norcasia",
  "Norosí",
  "Novita",
  "Nueva Granada",
  "Nuevo Colón",
  "Nunchía",
  "Nuquí",
  "Nariño",
  "Obando",
  "Ocaña",
  "Oiba",
  "Oicatá",
  "Olaya",
  "Olaya Herrera",
  "Onzaga",
  "Oporapa",
  "Orito",
  "Orocué",
  "Ortega",
  "Ospina",
  "Otanche",
  "Ovejas",
  "Pachavita",
  "Pacho",
  "Padilla",
  "Paicol",
  "Pailitas",
  "Paime",
  "Paipa",
  "Pajarito",
  "Palermo",
  "Palestina",
  "Palestina (Caldas)",
  "Palestina (Huila)",
  "Palmar",
  "Palmar de Varela",
  "Palmas del Socorro",
  "Palmira",
  "Palocabildo",
  "Páramo",
  "Páramo (Santander)",
  "Páez",
  "Páez (Cauca)",
  "Pajarito",
  "Pauna",
  "Paya",
  "Paz de Ariporo",
  "Paz de Río",
  "Pedraza",
  "Pelaya",
  "Pensilvania",
  "Peque",
  "Pereira",
  "Pesca",
  "Peñol",
  "Piamonte",
  "Pie de Cuesta",
  "Piedecuesta",
  "Piedras",
  "Piendamó",
  "Pijao",
  "Pijiño del Carmen",
  "Pinchote",
  "Pinillos",
  "Piojó",
  "Pisba",
  "Pital",
  "Pitalito",
  "Pivijay",
  "Planadas",
  "Planeta Rica",
  "Plato",
  "Policarpa",
  "Polonuevo",
  "Ponedera",
  "Popayán",
  "Pore",
  "Potosí",
  "Pradera",
  "Prado",
  "Providencia",
  "Providencia (Nariño)",
  "Pueblo Bello",
  "Pueblo Nuevo",
  "Pueblo Rico",
  "Pueblorrico",
  "Puerres",
  "Puerto Asís",
  "Puerto Berrío",
  "Puerto Boyacá",
  "Puerto Caicedo",
  "Puerto Carreño",
  "Puerto Colombia",
  "Puerto Concordia",
  "Puerto Escondido",
  "Puerto Gaitán",
  "Puerto Guzmán",
  "Puerto Leguízamo",
  "Puerto Libertador",
  "Puerto López",
  "Puerto Nare",
  "Puerto Nariño",
  "Puerto Rico",
  "Puerto Rico (Caquetá)",
  "Puerto Rico (Meta)",
  "Puerto Rondón",
  "Puerto Salgar",
  "Puerto Santander",
  "Puerto Tejada",
  "Puerto Triunfo",
  "Puerto Wilches",
  "Pulí",
  "Pupiales",
  "Puracé",
  "Purificación",
  "Purísima",
  "Quebradanegra",
  "Quetame",
  "Quibdó",
  "Quimbaya",
  "Quinchía",
  "Quipama",
  "Quipile",
  "Ragonvalia",
  "Ramiriquí",
  "Ráquira",
  "Recetor",
  "Regidor",
  "Remedios",
  "Remolino",
  "Repelón",
  "Restrepo",
  "Restrepo (Meta)",
  "Restrepo (Valle del Cauca)",
  "Ricaurte",
  "Ricaurte (Cundinamarca)",
  "Ricaurte (Nariño)",
  "Rioblanco",
  "Riofrío",
  "Riohacha",
  "Risaralda",
  "Rivera",
  "Roberto Payán",
  "Roldanillo",
  "Roncesvalles",
  "Rondón",
  "Rosas",
  "Rovira",
  "Ríonegro",
  "Ríonegro (Antioquia)",
  "Ríonegro (Santander)",
  "Ríosucio",
  "Ríosucio (Caldas)",
  "Ríosucio (Chocó)",
  "Ríoviejo",
  "Sabana de Torres",
  "Sabanagrande",
  "Sabanalarga",
  "Sabanalarga (Atlántico)",
  "Sabanalarga (Casanare)",
  "Sabanalarga (Santander)",
  "Sabanas de San Ángel",
  "Saboyá",
  "Sahagún",
  "Saladoblanco",
  "Salamina",
  "Salamina (Caldas)",
  "Salamina (Magdalena)",
  "Salazar",
  "Saldaña",
  "Salento",
  "Salgar",
  "Samaca",
  "Samaniego",
  "Samaná",
  "Sampués",
  "San Agustín",
  "San Alberto",
  "San Andrés",
  "San Andrés (Santander)",
  "San Andrés de Cuerquia",
  "San Andrés de Sotavento",
  "San Andrés de Tumaco",
  "San Antero",
  "San Antonio",
  "San Antonio de Tequendama",
  "San Antonio del Tequendama",
  "San Benito",
  "San Benito Abad",
  "San Bernardo",
  "San Bernardo (Cundinamarca)",
  "San Bernardo (Nariño)",
  "San Bernardo del Viento",
  "San Calixto",
  "San Carlos",
  "San Carlos (Antioquia)",
  "San Carlos (Córdoba)",
  "San Carlos de Guaroa",
  "San Cayetano",
  "San Cayetano (Cundinamarca)",
  "San Cayetano (Santander)",
  "San Cristóbal",
  "San Cristóbal (Bolívar)",
  "San Diego",
  "San Eduardo",
  "San Estanislao",
  "San Fernando",
  "San Francisco",
  "San Francisco (Antioquia)",
  "San Francisco (Cundinamarca)",
  "San Francisco (Putumayo)",
  "San Gil",
  "San Jacinto",
  "San Jacinto del Cauca",
  "San Javier",
  "San Jerónimo",
  "San Joaquín",
  "San José",
  "San José de la Montaña",
  "San José de Miranda",
  "San José de Pare",
  "San José del Fragua",
  "San José del Guaviare",
  "San José del Palmar",
  "San Juan de Arama",
  "San Juan de Betulia",
  "San Juan de Nepomuceno",
  "San Juan de Pasto",
  "San Juan de Río Seco",
  "San Juan del Cesar",
  "San Juan del Sur",
  "San Juanito",
  "San Lorenzo",
  "San Luis",
  "San Luis (Tolima)",
  "San Luis de Gaceno",
  "San Luis de Palenque",
  "San Marcos",
  "San Marcos (Sucre)",
  "San Martín",
  "San Martín (Cesar)",
  "San Martín (Meta)",
  "San Martín de Loba",
  "San Mateo",
  "San Miguel",
  "San Miguel (Putumayo)",
  "San Miguel (Santander)",
  "San Onofre",
  "San Pablo",
  "San Pablo (Bolívar)",
  "San Pablo (Nariño)",
  "San Pablo de Borbur",
  "San Pedro",
  "San Pedro (Antioquia)",
  "San Pedro (Córdoba)",
  "San Pedro (Sucre)",
  "San Pedro (Valle del Cauca)",
  "San Pedro de Cartago",
  "San Pedro de Urabá",
  "San Pelayo",
  "San Rafael",
  "San Rafael (Antioquia)",
  "San Roque",
  "San Sebastián",
  "San Sebastián (Cauca)",
  "San Sebastián de Buenavista",
  "San Vicente",
  "San Vicente (Antioquia)",
  "San Vicente de Chucurí",
  "San Vicente del Caguán",
  "San Vicente del Chucurí",
  "San Zenón",
  "Sandoná",
  "Santa Ana",
  "Santa Ana (Magdalena)",
  "Santa Bárbara",
  "Santa Bárbara (Antioquia)",
  "Santa Bárbara (Nariño)",
  "Santa Bárbara (Santander)",
  "Santa Bárbara de Pinto",
  "Santa Catalina",
  "Santa Fe de Antioquia",
  "Santa Genoveva de Docordó",
  "Santa Helena del Opón",
  "Santa Isabel",
  "Santa Lucía",
  "Santa Marta",
  "Santa María",
  "Santa María (Boyacá)",
  "Santa María (Huila)",
  "Santa Rosa",
  "Santa Rosa (Bolívar)",
  "Santa Rosa (Cauca)",
  "Santa Rosa de Cabal",
  "Santa Rosa de Osos",
  "Santa Rosa del Sur",
  "Santa Rosa de Viterbo",
  "Santa Rosalía",
  "Santa Sofía",
  "Santana",
  "Santander de Quilichao",
  "Santiago",
  "Santiago (Norte de Santander)",
  "Santiago (Putumayo)",
  "Santo Domingo",
  "Santo Domingo (Antioquia)",
  "Santo Tomás",
  "Santuario",
  "Santuario (Risaralda)",
  "Santuario (Santander)",
  "Sapuyes",
  "Saravena",
  "Sardinata",
  "Sasaima",
  "Sativanorte",
  "Sativasur",
  "Segovia",
  "Sesquilé",
  "Sevilla",
  "Sevilla (Valle del Cauca)",
  "Siachoque",
  "Siban",
  "Sibundoy",
  "Silos",
  "Silvania",
  "Silvia",
  "Simacota",
  "Simijaca",
  "Simití",
  "Sincelejo",
  "Sincé",
  "Sipí",
  "Sitionuevo",
  "Soacha",
  "Soatá",
  "Socha",
  "Socorro",
  "Sogamoso",
  "Solano",
  "Soledad",
  "Solita",
  "Somondoco",
  "Sonsón",
  "Sopetrán",
  "Sopó",
  "Sora",
  "Soracá",
  "Sotaquirá",
  "Sotara",
  "Sotará (Cauca)",
  "Sotará (Nariño)",
  "Suaita",
  "Suan",
  "Suaza",
  "Subachoque",
  "Sucre",
  "Sucre (Cauca)",
  "Sucre (Santander)",
  "Sucre (Sucre)",
  "Suesca",
  "Supatá",
  "Supía",
  "Suratá",
  "Susa",
  "Susacón",
  "Sutamarchán",
  "Sutatausa",
  "Suaza",
  "Sucre",
  "Susa",
  "Tadó",
  "Talaigua Nuevo",
  "Tamalameque",
  "Taminango",
  "Tangua",
  "Tarazá",
  "Tarqui",
  "Tarso",
  "Tasco",
  "Tauramena",
  "Tausa",
  "Tello",
  "Tena",
  "Tenerife",
  "Tenjo",
  "Tenza",
  "Teorama",
  "Teruel",
  "Tesalia",
  "Tibacuy",
  "Tibaná",
  "Tibasosa",
  "Tibirita",
  "Tibú",
  "Tierralta",
  "Timaná",
  "Timbío",
  "Timbiquí",
  "Tinjacá",
  "Tipacoque",
  "Tiquisio",
  "Titiribí",
  "Toca",
  "Tocaima",
  "Tocancipá",
  "Togüí",
  "Toledo",
  "Toledo (Antioquia)",
  "Toledo (Norte de Santander)",
  "Toledo (Santander)",
  "Tolú",
  "Tolú Viejo",
  "Tona",
  "Topaipí",
  "Toribío",
  "Toro",
  "Tota",
  "Totoró",
  "Trinidad",
  "Trujillo",
  "Tubará",
  "Tuchín",
  "Tulúa",
  "Tumaco",
  "Tunja",
  "Tununguá",
  "Turbaco",
  "Turbaná",
  "Turbo",
  "Turmequé",
  "Tuta",
  "Tutazá",
  "Túquerres",
  "Túquerres (Nariño)",
  "Túquerres (Santander)",
  "Ubalá",
  "Ubaque",
  "Ubate",
  "Ulloa",
  "Une",
  "Unguía",
  "Unión Panamericana",
  "Uramita",
  "Uribe",
  "Uribia",
  "Urrao",
  "Urumita",
  "Usiacurí",
  "Valdivia",
  "Valencia",
  "Valle de San José",
  "Valle de San Juan",
  "Valledupar",
  "Valparaiso",
  "Valparaiso (Antioquia)",
  "Valparaiso (Caquetá)",
  "Vélez",
  "Venadillo",
  "Venecia",
  "Venecia (Antioquia)",
  "Venecia (Cundinamarca)",
  "Ventaquemada",
  "Vergara",
  "Versalles",
  "Vetas",
  "Viani",
  "Vigía del Fuerte",
  "Vijes",
  "Villa Caro",
  "Villa de Leyva",
  "Villa del Rosario",
  "Villa del Rosario (Norte de Santander)",
  "Villa Rica",
  "Villagarzón",
  "Villagómez",
  "Villanueva",
  "Villanueva (Bolívar)",
  "Villanueva (Casanare)",
  "Villanueva (La Guajira)",
  "Villanueva (Santander)",
  "Villapinzón",
  "Villarrica",
  "Villavicencio",
  "Villavieja",
  "Villeta",
  "Viotá",
  "Viracachá",
  "Vista Hermosa",
  "Viterbo",
  "Yacopí",
  "Yacuanquer",
  "Yaguará",
  "Yalí",
  "Yarumal",
  "Yolombó",
  "Yondó",
  "Yopal",
  "Yotoco",
  "Yumbo",
  "Zambrano",
  "Zapatoca",
  "Zaragoza",
  "Zarzal",
  "Zetaquira",
  "Zipacón",
  "Zipaquirá",
  "Zona Bananera"
];